<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Idea;
use App\Models\User;
use App\Models\Category;
use App\Models\Comment;
use App\Models\Reaction;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class IdeaSeeder extends Seeder
{
    public function run(): void
    {
       // 1. Dọn dẹp dữ liệu cũ (Dành cho PostgreSQL)
        DB::statement('TRUNCATE TABLE reactions RESTART IDENTITY CASCADE');
        DB::statement('TRUNCATE TABLE comments RESTART IDENTITY CASCADE');
        DB::statement('TRUNCATE TABLE ideas RESTART IDENTITY CASCADE');

        // 2. Lấy danh sách ID cần thiết
        $staffIds = User::where('role', 'Staff')->pluck('userId')->toArray();
        $categories = [
            'Information Technology' => Category::firstOrCreate(['name' => 'Information Technology'], ['description' => 'IT infrastructure and software.']),
            'Business' => Category::firstOrCreate(['name' => 'Business'], ['description' => 'Business strategies and operations.']),
            'Design' => Category::firstOrCreate(['name' => 'Design'], ['description' => 'UI/UX and branding.'])
        ];

        if (empty($staffIds)) {
            $this->command->error('No Staff users found. Please seed Users table first!');
            return;
        }

        // --- TẠO FILE VẬT LÝ THẬT TRÊN Ổ CỨNG ---
        if (!Storage::disk('public')->exists('ideas')) {
            Storage::disk('public')->makeDirectory('ideas');
        }

        $dummyContent = "This is a sample PDF document generated by the system Seeder for testing download purposes. Project: Idea Management System 2026.";
        Storage::disk('public')->put('ideas/sample_document.pdf', $dummyContent);
        // ---------------------------------------

        // 3. Danh sách 20 ý tưởng English chuyên nghiệp
        $ideaData = [
            ['cat' => 'Information Technology', 'title' => 'AI-Driven Code Review Assistant', 'desc' => "Integrate AI into GitHub to automatically review pull requests and catch bugs early."],
            ['cat' => 'Information Technology', 'title' => 'Microservices Architecture Migration', 'desc' => "Transitioning our monolith to Docker/Kubernetes for better scalability."],
            ['cat' => 'Information Technology', 'title' => 'Zero Trust Security Implementation', 'desc' => "Replacing traditional VPNs with a Zero Trust model for remote work security."],
            ['cat' => 'Information Technology', 'title' => 'Cloud Cost Optimization Strategy', 'desc' => "Using spot instances and auto-scaling to reduce AWS monthly spending."],
            ['cat' => 'Information Technology', 'title' => 'Automated Vulnerability Scanning', 'desc' => "Embedding security tools like Snyk directly into our CI/CD pipelines."],
            ['cat' => 'Information Technology', 'title' => 'Internal Developer Knowledge Portal', 'desc' => "A centralized platform to manage documentation and API specifications."],
            ['cat' => 'Information Technology', 'title' => 'GraphQL for High-Performance Mobile APIs', 'desc' => "Migrating REST to GraphQL to eliminate data over-fetching in our app."],

            ['cat' => 'Business', 'title' => 'APAC Market Expansion Plan', 'desc' => "Allocating budget to localize products for the Japan and South Korea markets."],
            ['cat' => 'Business', 'title' => 'Employee Wellness & 4-Day Workweek', 'desc' => "Trialing a flexible schedule to boost productivity and reduce burnout."],
            ['cat' => 'Business', 'title' => 'Pivoting to SaaS Subscription Model', 'desc' => "Transitioning from one-time licenses to recurring monthly revenue."],
            ['cat' => 'Business', 'title' => 'Automated Client Onboarding Portal', 'desc' => "Reducing manual email tasks by 60% with a self-service B2B portal."],
            ['cat' => 'Business', 'title' => 'Eco-Friendly Sustainable Packaging', 'desc' => "Replacing plastic with biodegradable materials to boost brand image."],
            ['cat' => 'Business', 'title' => 'Loyalty Points & Referral System', 'desc' => "Increasing retention by rewarding users for purchases and social shares."],
            ['cat' => 'Business', 'title' => 'Flexible Remote Work Policy 2026', 'desc' => "Formalizing a hybrid model to attract top global talent."],

            ['cat' => 'Design', 'title' => 'System-wide Dark Mode Support', 'desc' => "Redesigning color palettes to support native dark themes on all devices."],
            ['cat' => 'Design', 'title' => 'Web Accessibility Compliance (WCAG)', 'desc' => "Updating contrast ratios and ARIA labels for better inclusivity."],
            ['cat' => 'Design', 'title' => 'Modern Minimalist Brand Identity', 'desc' => "A full refresh of our logo, typography, and marketing design system."],
            ['cat' => 'Design', 'title' => 'Interactive Gamification in Sign-up', 'desc' => "Adding progress bars and badges to delight users during onboarding."],
            ['cat' => 'Design', 'title' => 'Premium Unboxing Experience Concept', 'desc' => "Drafting new matte-texture packaging for our flagship product line."],
            ['cat' => 'Design', 'title' => '3D Virtual Product Showroom', 'desc' => "Using WebGL to allow customers to interact with 3D models online."]
        ];

        // 4. Tiến hành tạo Idea và Comment
        foreach ($ideaData as $index => $data) {
            $catId = $categories[$data['cat']]->categoryId;
            $uId = $staffIds[array_rand($staffIds)];

            // Xáo trộn: 1/3 số bài là bài cũ (đã đóng vote)
            $createdAt = ($index % 3 == 0)
                ? Carbon::now()->subWeeks(3)
                : Carbon::now()->subDays(rand(0, 3))->subHours(rand(1, 10));

            $idea = Idea::create([
                'categoryId' => $catId,
                'userId' => $uId,
                'title' => $data['title'],
                'description' => $data['desc'],
                'filePath' => 'ideas/sample_document.pdf', // Trỏ về file thật vừa tạo ở trên
                'is_anonymous' => (bool)rand(0, 1),
                'views' => rand(20, 900),
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
            ]);

            // Tạo 1-2 bình luận tiếng Anh ngẫu nhiên cho mỗi bài
            $sampleComments = ["Great proposal!", "Interesting approach.", "I support this idea.", "We should discuss the cost."];
            for ($i = 0; $i < rand(1, 2); $i++) {
                Comment::create([
                    'ideaId' => $idea->ideaId,
                    'userId' => $staffIds[array_rand($staffIds)],
                    'content' => $sampleComments[array_rand($sampleComments)],
                    'is_anonymous' => (bool)rand(0, 1),
                    'created_at' => $createdAt->copy()->addHours(rand(1, 24)),
                ]);
            }
        }

        $this->command->info('IdeaSeeder: 20 English entries and physical file generated successfully!');
    }
}
